name: "Update babashka"
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "39 3 * * 1"

jobs:
  clojure-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Update babashka version
        run: "nix run .#babashka-unwrapped.updateScript"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Update
          title: Update clojure dependencies
          assignees: jlesquembre
          branch: update-babahska
          labels: |
            dependencies
            automated
