name: "Update babashka"
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "39 3 * * 1"

jobs:
  clojure-deps:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/nix-installer-action@main

      - name: Update babashka version
        run: "nix run .#babashka-unwrapped.updateScript"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
          commit-message: Update
          title: Update babashka version
          assignees: jlesquembre
          branch: update-babahska
          labels: |
            dependencies
            automated
